### ISSUE TITLE
Change size of fullscreen container

### ISSUE THREAD

**Issue by t-book** [nicolas-t/Chocolat#108]
Hi,

I'm in the need to dynamically create and place the container used by chocolate.

1) user clicks chocolat__image
2) container is created based on header and viewport height
3) chocolat gallery is drawn into the container 

Is there some hook I can use to do something after an image has been clicked?

As alternative would it work to change the height of the fullWindow container to abstract the height of a navbar?

**Comment by nicolas-t** [comment]
Hello,

Your use case is not very clear, can you be more precise ?

> Is there some hook I can use to do something after an image has been clicked?

you can use `afterMarkup` or `afterImageLoad`

here is an example : 
https://github.com/nicolas-t/Chocolat/blob/399cf1c73712832788b324a4617bd55c780a18f5/test/test.chocolat.js#L153-L162

**Comment by t-book** [comment]
@nicolas-t thanks for your reply and sorry for being unclear. My question might be quite easy. Let's say you have a big long single page with some sticky-top navbar. 

Now from somewhere, a chocolat gallery is opened as fullwindow. Due to the z-index of the navbar the closing button of the gallery might be covered further the image is not centered. What I'm looking for is a way to change the  height of a fullwindow gallery to take the remaining space (viewport minus navbar)

It might work to just give the gallery some top-margin based on the viewport height? Unfortuantely I can only test this evening when back in office.

**Comment by nicolas-t** [comment]
In your css you can add 

```css

body .chocolat-overlay{
    left:0;
    bottom:0;
    right: 0;
    top: 60px; /* height of the topbar */
    height: auto;
    width: auto;
}
body .chocolat-wrapper{
    left:0;
    bottom:0;
    right: 0;
    top: 60px; /* height of the topbar */
    height: auto;
    width: auto;
}
```

I think it'll do the job
