### ISSUE TITLE
page-layout is moving

### ISSUE THREAD

**Issue by PetersOtto** [nicolas-t/Chocolat#122]
Hi Nicolas, 

I have just a question.
When I close the lightbox the page-layout is moving. Its because the scrollbar disappears when the lightbox is open and appears when lightbox is close.

I could use "overflow: scroll;" but then the scrollbar is visible in the lightbox.

Do you have an Idea how I could solve the problem? 

Best regards

**Comment by nicolas-t** [comment]
Hello,

You can try :
```css
body.chocolat-open {
    overflow: auto; /* Keep the scrollbar */
}
```
Or 
```css
body.chocolat-open {
    overflow: hidden; /* Hide the scrollbar */
    padding-right: 17px; /* Replace it with a margin to avoid layout jumping */
}
```

The 17px trick is the one used by twitter, margin size may depend on the os/browser, but, you get the idea.

Somewhat related discussion here : https://stackoverflow.com/questions/1417934/how-to-prevent-scrollbar-from-repositioning-web-page
